# Generated by Django 5.0.1 on 2024-01-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumpdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dumpdata',
            options={'managed': False, 'verbose_name': 'Zrzut danych z bazy', 'verbose_name_plural': 'Zrzut danych z bazy'},
        ),
    ]
