# Generated by Django 5.0.1 on 2024-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingoption',
            name='voting',
        ),
        migrations.AlterField(
            model_name='votingoption',
            name='option_value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
