# Generated by Django 5.0.1 on 2024-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_votingoption_voting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='options',
        ),
        migrations.AddField(
            model_name='voting',
            name='options',
            field=models.ManyToManyField(related_name='+', to='vote.votingoption'),
        ),
    ]
